"""Chart decision audit contracts."""

from core.chart_audit.actual_event_overlay import (
    actual_marker_from_event,
    actual_markers_from_events,
    actual_markers_from_records,
    actual_markers_from_trade_rows,
    normalize_block_reason,
)
from core.chart_audit.chart_audit_service import get_pair_decision_audit_chart
from core.chart_audit.marker_types import (
    ActualAdvancedMLShadowRecommendationMarker,
    ActualBlockedSignalMarker,
    ActualEntryMarker,
    ActualExitMarker,
    ActualManualExitMarker,
    ActualMarker,
    ActualMarkerBase,
    ActualMarkerType,
    ActualPartialExitMarker,
    ActualRegimeExitMarker,
    BlockReason,
    CuratorState,
    MarkerCategory,
    ReplayMarkerType,
    StatisticalMarkerType,
    build_actual_entry_id,
    build_replay_entry_id,
)
from core.chart_audit.timestamp_alignment import (
    TIMESTAMP_ALIGNMENT_EXACT,
    TIMESTAMP_ALIGNMENT_SNAPPED_TO_NEAREST_CANDLE,
    align_actual_marker_timestamp,
    align_actual_marker_timestamps,
)

__all__ = [
    "actual_marker_from_event",
    "actual_markers_from_events",
    "actual_markers_from_records",
    "actual_markers_from_trade_rows",
    "normalize_block_reason",
    "get_pair_decision_audit_chart",
    "ActualAdvancedMLShadowRecommendationMarker",
    "ActualBlockedSignalMarker",
    "ActualEntryMarker",
    "ActualExitMarker",
    "ActualManualExitMarker",
    "ActualMarker",
    "ActualMarkerBase",
    "ActualMarkerType",
    "ActualPartialExitMarker",
    "ActualRegimeExitMarker",
    "BlockReason",
    "CuratorState",
    "MarkerCategory",
    "ReplayMarkerType",
    "StatisticalMarkerType",
    "TIMESTAMP_ALIGNMENT_EXACT",
    "TIMESTAMP_ALIGNMENT_SNAPPED_TO_NEAREST_CANDLE",
    "align_actual_marker_timestamp",
    "align_actual_marker_timestamps",
    "build_actual_entry_id",
    "build_replay_entry_id",
]
