"""Run history

Revision ID: 2a6341d32e9c
Revises: 0005_refresh_token_persistence
Create Date: 2026-04-13 22:30:42.197405
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '2a6341d32e9c'
down_revision = '0005_refresh_token_persistence'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

